FROM debian

ENV WINEDEBUG=-all

RUN INSTALL_DEPS=' \
  ca-certificates \
  curl \
  gnupg2 \
  ' \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install --no-install-recommends -y $INSTALL_DEPS \
  gosu \
  && curl https://dl.winehq.org/wine-builds/winehq.key -sSf | gpg --dearmor > /usr/share/keyrings/winehq.gpg \
  && . /etc/os-release \
  && echo "deb [signed-by=/usr/share/keyrings/winehq.gpg] https://dl.winehq.org/wine-builds/debian/ $VERSION_CODENAME main" > /etc/apt/sources.list.d/wine-builds.list \
  && dpkg --add-architecture i386 \
  && apt-get update \
  && apt-get install --no-install-recommends -y \
  winehq-stable \
  && apt-get purge -y --auto-remove $INSTALL_DEPS \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && useradd -m user \
  && gosu user wine cmd.exe /c echo. > /dev/null 2>&1

RUN export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install --no-install-recommends -y \
  ca-certificates \
  curl \
  gcc \
  libc-dev \
  mingw-w64 \
  unzip \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && gosu user sh -c " \
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
  && . \$HOME/.cargo/env \
  && rustup target add i686-pc-windows-gnu \
  "

RUN USER=user \
  && GROUP=user \
  && curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.5.1/fixuid-0.5.1-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - \
  && chown root:root /usr/local/bin/fixuid \
  && chmod 4755 /usr/local/bin/fixuid \
  && mkdir -p /etc/fixuid \
  && printf "user: $USER\ngroup: $GROUP\n" > /etc/fixuid/config.yml

EXPOSE 21569
USER user
WORKDIR /home/user
ENTRYPOINT ["fixuid"]
