on:
  push:
    branches:
      - master

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      cross-version: 0.2.1
      cross-docker-image: rustembedded/cross:i686-pc-windows-gnu
    outputs:
      version: ${{ steps.version.outputs.CARGO_PKG_VERSION }}

    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/extract-aqtk.sh

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-pc-windows-gnu
      - name: Cache Cross
        id: cache-cross
        uses: actions/cache@v2
        with:
          path: ~/cross
          key: ${{ runner.os }}-cross-${{ env.cross-version }}-${{ env.cross-docker-image }}
      - name: Install Cross
        if: steps.cache-cross.outputs.cache-hit != 'true'
        run: |
          mkdir ~/cross \
          && cargo install --version=${{ env.cross-version }} cross \
          && cp ~/.cargo/bin/cross ~/cross/ \
          && docker pull ${{ env.cross-docker-image }} \
          && docker save -o ~/cross/image.tar ${{ env.cross-docker-image }} \
      - name: Use Cached Cross
        if: steps.cache-cross.outputs.cache-hit == 'true'
        run: |
          cp ~/cross/cross ~/.cargo/bin/ \
          && docker load -i ~/cross/image.tar

      - name: Build
        run: cross build --color=always --target i686-pc-windows-gnu --release

      - name: Get version
        id: version
        run: |
          cargo metadata --format-version=1 --no-deps \
          | jq -r '"::set-output name=CARGO_PKG_VERSION::" + .packages[].version'
      - name: Package
        run: |
          mkdir release && cd release \
          && mv ../target/i686-pc-windows-gnu/release/aquestalk-proxyd.exe ./aquestalk-proxy.exe \
          && mv ../aquestalk ./aquestalk \
          && cp ../README.md ./ \
          && cp ../COPYING ./ \
          && zip -r ../aquestalk-proxy_v${{ steps.version.outputs.CARGO_PKG_VERSION }}.zip *
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.CARGO_PKG_VERSION }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            aquestalk-proxy_v${{ steps.version.outputs.CARGO_PKG_VERSION }}.zip
