on:
  push:
    branches:
      - master

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    env:
      cross-version: 0.2.5
      cross-docker-image: rustembedded/cross@sha256:3ec96578f30fe9c70214d4e3ad784be2722d1db453555b03501f483ff8a9aac4
    outputs:
      version: ${{ steps.version.outputs.CARGO_PKG_VERSION }}

    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/extract-aqtk.sh

      - name: Cache Cross
        id: cache-cross
        uses: actions/cache@v4
        with:
          path: ~/cross
          key: ${{ runner.os }}-cross-${{ env.cross-version }}-${{ env.cross-docker-image }}
      - name: Install Cross
        if: steps.cache-cross.outputs.cache-hit != 'true'
        run: |
          mkdir ~/cross \
          && cargo --color=always install cross@${{ env.cross-version }} \
          && cp ~/.cargo/bin/cross ~/cross/ \
          && docker pull ${{ env.cross-docker-image }} \
          && docker save -o ~/cross/image.tar ${{ env.cross-docker-image }} \
      - name: Use Cached Cross
        if: steps.cache-cross.outputs.cache-hit == 'true'
        run: |
          cp ~/cross/cross ~/.cargo/bin/ \
          && docker load -i ~/cross/image.tar

      - name: Build
        run: |
          echo -e "[target.i686-pc-windows-gnu]\nimage = \"${{ env.cross-docker-image }}\"" > Cross.toml \
          && cross build --color=always --target i686-pc-windows-gnu --release

      - name: Get version
        id: version
        run: |
          cargo --color=always metadata --format-version=1 --no-deps \
          | jq -r '"CARGO_PKG_VERSION=" + .packages[].version' >> $GITHUB_OUTPUT
      - name: Package
        run: |
          mkdir release && cd release \
          && mv ../target/i686-pc-windows-gnu/release/aquestalk-proxyd.exe ./aquestalk-proxy.exe \
          && mv ../aquestalk ./aquestalk \
          && cp ../README.md ./ \
          && cp ../COPYING ./ \
          && zip -r ../aquestalk-proxy_v${{ steps.version.outputs.CARGO_PKG_VERSION }}.zip *
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.CARGO_PKG_VERSION }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            aquestalk-proxy_v${{ steps.version.outputs.CARGO_PKG_VERSION }}.zip
